#!/usr/bin/env bash

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

#-------- Runtime ----------

# Reset containers
fin project reset --force

# Install Gatsby CLI locally
echo -e "${yellow}Installing the Gatsby CLI${NC}"
cd "$PROJECT_ROOT"
fin exec npm install gatsby-cli || exit 1

# Install new site
fin install

# Start development server
fin develop